language: android

jdk:
  - oraclejdk8

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/

env:
  global:
    - ADB_INSTALL_TIMEOUT=20
  matrix:
    - ANDROID_TARGET=android-25 ANDROID_ABI=x86

licenses:
 - android-sdk-preview-license-.+
 - android-sdk-license-.+
 - google-gdk-license-.+

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # to install new Android SDK tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - android-25

    # Support library
    - extra-android-support
    - extra-android-m2repository

before_install:

    - mkdir "$ANDROID_HOME/licenses" || true
    - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
    - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
    - chmod +x gradlew
    - ./gradlew dependencies || true

#install:
  ## List and delete unnecessary components to free space
  #- echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  #- echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"

script:
  - ./gradlew clean
  - ./gradlew check # Local unit tests
